In [1]:
import pandas as pd

In [6]:
melb_df = pd.read_csv('melb_data.csv')

# Muestra el csv leído
#melb_df

# Dice lo que tiene cada columna
melb_df.describe()

,Unnamed: 0,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,18396.000000,18396.000000,1.839600e+04,18395.000000,18395.000000,14927.000000,14925.000000,14820.000000,13603.000000,7762.000000,8958.000000,15064.000000,15064.000000,18395.000000
mean,11826.787073,2.935040,1.056697e+06,10.389986,3107.140147,2.913043,1.538492,1.615520,558.116371,151.220219,1965.879996,-37.809849,144.996338,7517.975265
std,6800.710448,0.958202,6.419217e+05,6.009050,95.000995,0.964641,0.689311,0.955916,3987.326586,519.188596,37.013261,0.081152,0.106375,4488.416599
min,1.000000,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,5936.750000,2.000000,6.330000e+05,6.300000,3046.000000,2.000000,1.000000,1.000000,176.500000,93.000000,1950.000000,-37.858100,144.931193,4294.000000
50%,11820.500000,3.000000,8.800000e+05,9.700000,3085.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.803625,145.000920,6567.000000
75%,17734.250000,3.000000,1.302000e+06,13.300000,3149.000000,3.000000,2.000000,2.000000,651.000000,174.000000,2000.000000,-37.756270,145.060000,10331.000000
max,23546.000000,12.000000,9.000000e+06,48.100000,3978.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [9]:
# Quitamos cualquier fila que tenga un missing value
melb_df = melb_df.dropna(axis = 0)
melb_df

melb_df.describe()

,Unnamed: 0,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,6196.000000,6196.000000,6.196000e+03,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000
mean,9632.061491,2.931407,1.068828e+06,9.751097,3101.947708,2.902034,1.576340,1.573596,471.006940,141.568645,1964.081988,-37.807904,144.990201,7435.489509
std,5743.219058,0.971079,6.751564e+05,5.612065,86.421604,0.970055,0.711362,0.929947,897.449881,90.834824,38.105673,0.075850,0.099165,4337.698917
min,2.000000,1.000000,1.310000e+05,0.000000,3000.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1196.000000,-38.164920,144.542370,389.000000
25%,4544.750000,2.000000,6.200000e+05,5.900000,3044.000000,2.000000,1.000000,1.000000,152.000000,91.000000,1940.000000,-37.855438,144.926198,4383.750000
50%,9346.500000,3.000000,8.800000e+05,9.000000,3081.000000,3.000000,1.000000,1.000000,373.000000,124.000000,1970.000000,-37.802250,144.995800,6567.000000
75%,14544.750000,4.000000,1.325000e+06,12.400000,3147.000000,3.000000,2.000000,2.000000,628.000000,170.000000,2000.000000,-37.758200,145.052700,10175.000000
max,19739.000000,8.000000,9.000000e+06,47.400000,3977.000000,9.000000,8.000000,10.000000,37000.000000,3112.000000,2018.000000,-37.457090,145.526350,21650.000000

In [10]:
# La variable a predecir va a ser "Price". Variable y
# Las variables numéricas para entrenar el modelo y realizar la predicción del precio, las que considero más idóneas. Las x son los predictores
y = melb_df['Price']
x = melb_df[['Rooms','Bathroom','Landsize','Lattitude','Longtitude']]

In [11]:
# Ejemplo con un DecisionTreeRegresor. Para variables númericas. Le vamos a pasar todas las filas cribadas
from sklearn.tree import DecisionTreeRegressor
melbourne_model = DecisionTreeRegressor()
melbourne_model.fit(x,y)

DecisionTreeRegressor()

In [12]:
# Predicciones para las 5 primeras casas
print("Prediciones para las 5 primeras casas: ")
print(x.head())
print("El precio real es: ")
print(y.head())
print("Las predicciones son: ")
print(melbourne_model.predict(x.head()))

Prediciones para las 5 primeras casas:
   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954
El precio real es:
1    1035000.0
2    1465000.0
4    1600000.0
6    1876000.0
7    1636000.0
Name: Price, dtype: float64
Las predicciones son:
[1035000. 1465000. 1600000. 1876000. 1636000.]

In [13]:
# MAE (Mean Absolute Error) Calcula el error que comete la predicción por cada y los suma todos
# Se hace en términos absolutos. Listamos haciendo las predicciones sobre las casas con las que entrenamos el modelo
from sklearn.metrics import mean_absolute_error
predicted_home_prices = melbourne_model.predict(x)
mean_absolute_error(y, predicted_home_prices)

1115.7467183128902

In [14]:
# Si tengo 10.000 filas con datos, la técnica en MD es dividir en 5.000 para entrenar y 5.000 para predecir.
# x para entrenar y x para validar
from sklearn.model_selection import train_test_split
train_x, val_x, train_y, val_y = train_test_split(x,y)

melbourne_model = DecisionTreeRegressor()
melbourne_model.fit(train_x, train_y)

val_predictions = melbourne_model.predict(val_x)
print(mean_absolute_error(val_y, val_predictions))

263235.4760060254

In [16]:
# Vamos a probar con 5, 50, 500, 5.000 a ver con cuantas filas tenemos la mejor predicción.
# El mejor es con 500
def get_mae(max_leaf_nodes, train_x, val_x, train_y, val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes)
    model.fit(train_x, train_y)
    preds_val = model.predict(val_x)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)

for max_leaf_nodes in [5, 50, 500, 5000]:
    my_mae = get_mae(max_leaf_nodes, train_x, val_x, train_y, val_y)
    print("Max leaf nodes: %d  \t\t Mean Absolute Error:  %d" %(max_leaf_nodes, my_mae))

Max leaf nodes: 5  		 Mean Absolute Error:  354838
Max leaf nodes: 50  		 Mean Absolute Error:  270773
Max leaf nodes: 500  		 Mean Absolute Error:  243281
Max leaf nodes: 5000  		 Mean Absolute Error:  257871